spring.application.name=demo
# Change the server port so it doesn't clash with anything else
server.port=8081

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://neondb_owner:npg_6Vmo4YyizRrg@ep-bold-waterfall-amecjnlr.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6Vmo4YyizRrg
# Tell Spring Boot to auto-create your tables!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true